### ISSUE TITLE
NAOTalker can't find Choregrapher

### ISSUE THREAD

**Issue by sebastianAnger** [ElliotGestrin/NAOChat#7]
Hello, I’m newbie and learning about NAO robot and I liked your project. I have the following problem:

```
PS C:\NAOChat-main>c:/NAOChat-main/main.py
Traceback (most recent call last):
  File "c:\NAOChat-main\main.py", line 50, in <module>
    case "nao": talker = NAOTalker(
                         ^^^^^^^^^^
```
```
  File "c:\NAOChat-main\src\NAO\NAOTalker.py", line 25, in _init_
    raise RuntimeError(f"NAOTalker can't find Choregrapher at {root_dir}")
RuntimeError: NAOTalker can't find Choregrapher at C:\NAOChat-main
```

I don’t understand if I need to have the project within the ‘Choregrapher’ program or if it should be linked to it. I don’t understand the communication between your NAOchat project and ‘Choregrapher’.

thank friend.

**Comment by ElliotGestrin** [comment]
Hi! Glad you find NAOChat interesting.

Have you followed the [NAO Readme](https://github.com/ElliotGestrin/NAOChat/tree/main/src/NAO)? It includes the commands to set up Choregrapher and PyNaoQI. 

For Choregrapher, it will look at the root directory ("C:\NAOChat-main" in your case) for the file choregrapher file.

If following that readme doesn't help, get back to me.
